
name: "testng Groovy ubuntu Building Java Applications CI workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  testng-groovy-java-gradle-ubuntu-latest:
    name: "Building Java Applications Sample Groovy testng"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    - name: "Building Java Applications Sample Groovy testng"
      run: |
          mkdir demo && cd demo
          # gradle init --project-name demo --type java-application --dsl groovy
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run
          echo "==================Bundle the application=================================================================="              
          ./gradlew build           
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle         

  testng-groovy-java-gradle-ubuntu-2004:
    name: "Building Java Applications Sample Groovy testng"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    - name: "Building Java Applications Sample Groovy testng"
      run: |
          mkdir demo && cd demo
          # gradle init --project-name demo --type java-application --dsl groovy
          gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run
          echo "==================Bundle the application=================================================================="              
          ./gradlew build           
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle 

  testng-groovy-java-gradle-ubuntu-1804:
    name: "Building Java Applications Sample Groovy testng"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    - name: "Building Java Applications Sample Groovy testng"
      run: |
          mkdir demo && cd demo
          # gradle init --project-name demo --type java-application --dsl groovy
          gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run
          echo "==================Bundle the application=================================================================="              
          ./gradlew build           
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle           